apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-app
  labels:
    app: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-cont
          image: nginx
